/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WatchLiveRouteImport } from './routes/watch-live'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as SitemapsRouteImport } from './routes/sitemaps'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SenateRouteImport } from './routes/senate'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PubRouteImport } from './routes/pub'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as PlenariesRouteImport } from './routes/plenaries'
import { Route as ParliamentaryMissionsRouteImport } from './routes/parliamentary-missions'
import { Route as ParliamentaryDiplomacyRouteImport } from './routes/parliamentary-diplomacy'
import { Route as ParliamentRouteImport } from './routes/parliament'
import { Route as OpinionRouteImport } from './routes/opinion'
import { Route as NetworkingRouteImport } from './routes/networking'
import { Route as NationalAssemblyRouteImport } from './routes/national-assembly'
import { Route as LegislatureRouteImport } from './routes/legislature'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstituencyActionsRouteImport } from './routes/constituency-actions'
import { Route as CommitteeEchoesRouteImport } from './routes/committee-echoes'
import { Route as BillsLawsRouteImport } from './routes/bills-laws'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as VerifyEmployeeIdRouteImport } from './routes/verify-employee.$id'
import { Route as PremiumPreviewIdRouteImport } from './routes/premium-preview.$id'
import { Route as ParliamentMpsRouteImport } from './routes/parliament.mps'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal.terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as LegalEditorialPolicyRouteImport } from './routes/legal.editorial-policy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalCopyrightNoticeRouteImport } from './routes/legal.copyright-notice'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPremiumRouteImport } from './routes/admin.premium'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMpsRouteImport } from './routes/admin.mps'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMagazinesRouteImport } from './routes/admin.magazines'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAuthorsRouteImport } from './routes/admin.authors'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminPortalSlugRouteImport } from './routes/admin-portal.$slug'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsCreateRouteImport } from './routes/admin.posts.create'
import { Route as AdminPostsSlugRouteImport } from './routes/admin.posts.$slug'
import { Route as AdminPostsSlugEditRouteImport } from './routes/admin.posts.$slug.edit'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLiveRoute = WatchLiveRouteImport.update({
  id: '/watch-live',
  path: '/watch-live',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsRoute = SitemapsRouteImport.update({
  id: '/sitemaps',
  path: '/sitemaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SenateRoute = SenateRouteImport.update({
  id: '/senate',
  path: '/senate',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PubRoute = PubRouteImport.update({
  id: '/pub',
  path: '/pub',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const PlenariesRoute = PlenariesRouteImport.update({
  id: '/plenaries',
  path: '/plenaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentaryMissionsRoute = ParliamentaryMissionsRouteImport.update({
  id: '/parliamentary-missions',
  path: '/parliamentary-missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentaryDiplomacyRoute = ParliamentaryDiplomacyRouteImport.update({
  id: '/parliamentary-diplomacy',
  path: '/parliamentary-diplomacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentRoute = ParliamentRouteImport.update({
  id: '/parliament',
  path: '/parliament',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionRoute = OpinionRouteImport.update({
  id: '/opinion',
  path: '/opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingRoute = NetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalAssemblyRoute = NationalAssemblyRouteImport.update({
  id: '/national-assembly',
  path: '/national-assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislatureRoute = LegislatureRouteImport.update({
  id: '/legislature',
  path: '/legislature',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstituencyActionsRoute = ConstituencyActionsRouteImport.update({
  id: '/constituency-actions',
  path: '/constituency-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeEchoesRoute = CommitteeEchoesRouteImport.update({
  id: '/committee-echoes',
  path: '/committee-echoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsLawsRoute = BillsLawsRouteImport.update({
  id: '/bills-laws',
  path: '/bills-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const VerifyEmployeeIdRoute = VerifyEmployeeIdRouteImport.update({
  id: '/verify-employee/$id',
  path: '/verify-employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumPreviewIdRoute = PremiumPreviewIdRouteImport.update({
  id: '/premium-preview/$id',
  path: '/premium-preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentMpsRoute = ParliamentMpsRouteImport.update({
  id: '/mps',
  path: '/mps',
  getParentRoute: () => ParliamentRoute,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalEditorialPolicyRoute = LegalEditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCopyrightNoticeRoute = LegalCopyrightNoticeRouteImport.update({
  id: '/copyright-notice',
  path: '/copyright-notice',
  getParentRoute: () => LegalRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiumRoute = AdminPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMpsRoute = AdminMpsRouteImport.update({
  id: '/mps',
  path: '/mps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMagazinesRoute = AdminMagazinesRouteImport.update({
  id: '/magazines',
  path: '/magazines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortalSlugRoute = AdminPortalSlugRouteImport.update({
  id: '/admin-portal/$slug',
  path: '/admin-portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsSlugRoute = AdminPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsSlugEditRoute = AdminPostsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPostsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRoute
  '/audio': typeof AudioRoute
  '/awards': typeof AwardsRoute
  '/bills-laws': typeof BillsLawsRoute
  '/committee-echoes': typeof CommitteeEchoesRoute
  '/constituency-actions': typeof ConstituencyActionsRoute
  '/contact': typeof ContactRoute
  '/economy': typeof EconomyRoute
  '/government': typeof GovernmentRoute
  '/interviews': typeof InterviewsRoute
  '/legal': typeof LegalRouteWithChildren
  '/legislature': typeof LegislatureRoute
  '/national-assembly': typeof NationalAssemblyRoute
  '/networking': typeof NetworkingRoute
  '/opinion': typeof OpinionRoute
  '/parliament': typeof ParliamentRouteWithChildren
  '/parliamentary-diplomacy': typeof ParliamentaryDiplomacyRoute
  '/parliamentary-missions': typeof ParliamentaryMissionsRoute
  '/plenaries': typeof PlenariesRoute
  '/politics': typeof PoliticsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/pub': typeof PubRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/senate': typeof SenateRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemaps': typeof SitemapsRoute
  '/system-status': typeof SystemStatusRoute
  '/video': typeof VideoRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRoute
  '/admin-portal/$slug': typeof AdminPortalSlugRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/magazines': typeof AdminMagazinesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/mps': typeof AdminMpsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/copyright-notice': typeof LegalCopyrightNoticeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/editorial-policy': typeof LegalEditorialPolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/parliament/mps': typeof ParliamentMpsRoute
  '/premium-preview/$id': typeof PremiumPreviewIdRoute
  '/verify-employee/$id': typeof VerifyEmployeeIdRoute
  '/legal/': typeof LegalIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRoute
  '/audio': typeof AudioRoute
  '/awards': typeof AwardsRoute
  '/bills-laws': typeof BillsLawsRoute
  '/committee-echoes': typeof CommitteeEchoesRoute
  '/constituency-actions': typeof ConstituencyActionsRoute
  '/contact': typeof ContactRoute
  '/economy': typeof EconomyRoute
  '/government': typeof GovernmentRoute
  '/interviews': typeof InterviewsRoute
  '/legislature': typeof LegislatureRoute
  '/national-assembly': typeof NationalAssemblyRoute
  '/networking': typeof NetworkingRoute
  '/opinion': typeof OpinionRoute
  '/parliament': typeof ParliamentRouteWithChildren
  '/parliamentary-diplomacy': typeof ParliamentaryDiplomacyRoute
  '/parliamentary-missions': typeof ParliamentaryMissionsRoute
  '/plenaries': typeof PlenariesRoute
  '/politics': typeof PoliticsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/pub': typeof PubRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/senate': typeof SenateRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemaps': typeof SitemapsRoute
  '/system-status': typeof SystemStatusRoute
  '/video': typeof VideoRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRoute
  '/admin-portal/$slug': typeof AdminPortalSlugRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/magazines': typeof AdminMagazinesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/mps': typeof AdminMpsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/copyright-notice': typeof LegalCopyrightNoticeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/editorial-policy': typeof LegalEditorialPolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/parliament/mps': typeof ParliamentMpsRoute
  '/premium-preview/$id': typeof PremiumPreviewIdRoute
  '/verify-employee/$id': typeof VerifyEmployeeIdRoute
  '/legal': typeof LegalIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRoute
  '/audio': typeof AudioRoute
  '/awards': typeof AwardsRoute
  '/bills-laws': typeof BillsLawsRoute
  '/committee-echoes': typeof CommitteeEchoesRoute
  '/constituency-actions': typeof ConstituencyActionsRoute
  '/contact': typeof ContactRoute
  '/economy': typeof EconomyRoute
  '/government': typeof GovernmentRoute
  '/interviews': typeof InterviewsRoute
  '/legal': typeof LegalRouteWithChildren
  '/legislature': typeof LegislatureRoute
  '/national-assembly': typeof NationalAssemblyRoute
  '/networking': typeof NetworkingRoute
  '/opinion': typeof OpinionRoute
  '/parliament': typeof ParliamentRouteWithChildren
  '/parliamentary-diplomacy': typeof ParliamentaryDiplomacyRoute
  '/parliamentary-missions': typeof ParliamentaryMissionsRoute
  '/plenaries': typeof PlenariesRoute
  '/politics': typeof PoliticsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/pub': typeof PubRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/senate': typeof SenateRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemaps': typeof SitemapsRoute
  '/system-status': typeof SystemStatusRoute
  '/video': typeof VideoRoute
  '/watch-live': typeof WatchLiveRoute
  '/weather': typeof WeatherRoute
  '/admin-portal/$slug': typeof AdminPortalSlugRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/magazines': typeof AdminMagazinesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/mps': typeof AdminMpsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/copyright-notice': typeof LegalCopyrightNoticeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/editorial-policy': typeof LegalEditorialPolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/parliament/mps': typeof ParliamentMpsRoute
  '/premium-preview/$id': typeof PremiumPreviewIdRoute
  '/verify-employee/$id': typeof VerifyEmployeeIdRoute
  '/legal/': typeof LegalIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/app'
    | '/audio'
    | '/awards'
    | '/bills-laws'
    | '/committee-echoes'
    | '/constituency-actions'
    | '/contact'
    | '/economy'
    | '/government'
    | '/interviews'
    | '/legal'
    | '/legislature'
    | '/national-assembly'
    | '/networking'
    | '/opinion'
    | '/parliament'
    | '/parliamentary-diplomacy'
    | '/parliamentary-missions'
    | '/plenaries'
    | '/politics'
    | '/premium'
    | '/profile'
    | '/pub'
    | '/reset-password'
    | '/rss.xml'
    | '/senate'
    | '/sign-in'
    | '/sitemap.xml'
    | '/sitemaps'
    | '/system-status'
    | '/video'
    | '/watch-live'
    | '/weather'
    | '/admin-portal/$slug'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/api'
    | '/admin/authors'
    | '/admin/banners'
    | '/admin/comments'
    | '/admin/employees'
    | '/admin/finance'
    | '/admin/live'
    | '/admin/magazines'
    | '/admin/media'
    | '/admin/mps'
    | '/admin/newsletter'
    | '/admin/premium'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/article/$slug'
    | '/auth/callback'
    | '/legal/copyright-notice'
    | '/legal/disclaimer'
    | '/legal/editorial-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/parliament/mps'
    | '/premium-preview/$id'
    | '/verify-employee/$id'
    | '/legal/'
    | '/admin/posts/$slug'
    | '/admin/posts/create'
    | '/admin/posts/'
    | '/admin/posts/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/app'
    | '/audio'
    | '/awards'
    | '/bills-laws'
    | '/committee-echoes'
    | '/constituency-actions'
    | '/contact'
    | '/economy'
    | '/government'
    | '/interviews'
    | '/legislature'
    | '/national-assembly'
    | '/networking'
    | '/opinion'
    | '/parliament'
    | '/parliamentary-diplomacy'
    | '/parliamentary-missions'
    | '/plenaries'
    | '/politics'
    | '/premium'
    | '/profile'
    | '/pub'
    | '/reset-password'
    | '/rss.xml'
    | '/senate'
    | '/sign-in'
    | '/sitemap.xml'
    | '/sitemaps'
    | '/system-status'
    | '/video'
    | '/watch-live'
    | '/weather'
    | '/admin-portal/$slug'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/api'
    | '/admin/authors'
    | '/admin/banners'
    | '/admin/comments'
    | '/admin/employees'
    | '/admin/finance'
    | '/admin/live'
    | '/admin/magazines'
    | '/admin/media'
    | '/admin/mps'
    | '/admin/newsletter'
    | '/admin/premium'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/article/$slug'
    | '/auth/callback'
    | '/legal/copyright-notice'
    | '/legal/disclaimer'
    | '/legal/editorial-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/parliament/mps'
    | '/premium-preview/$id'
    | '/verify-employee/$id'
    | '/legal'
    | '/admin/posts/$slug'
    | '/admin/posts/create'
    | '/admin/posts'
    | '/admin/posts/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/app'
    | '/audio'
    | '/awards'
    | '/bills-laws'
    | '/committee-echoes'
    | '/constituency-actions'
    | '/contact'
    | '/economy'
    | '/government'
    | '/interviews'
    | '/legal'
    | '/legislature'
    | '/national-assembly'
    | '/networking'
    | '/opinion'
    | '/parliament'
    | '/parliamentary-diplomacy'
    | '/parliamentary-missions'
    | '/plenaries'
    | '/politics'
    | '/premium'
    | '/profile'
    | '/pub'
    | '/reset-password'
    | '/rss.xml'
    | '/senate'
    | '/sign-in'
    | '/sitemap.xml'
    | '/sitemaps'
    | '/system-status'
    | '/video'
    | '/watch-live'
    | '/weather'
    | '/admin-portal/$slug'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/api'
    | '/admin/authors'
    | '/admin/banners'
    | '/admin/comments'
    | '/admin/employees'
    | '/admin/finance'
    | '/admin/live'
    | '/admin/magazines'
    | '/admin/media'
    | '/admin/mps'
    | '/admin/newsletter'
    | '/admin/premium'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/article/$slug'
    | '/auth/callback'
    | '/legal/copyright-notice'
    | '/legal/disclaimer'
    | '/legal/editorial-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/parliament/mps'
    | '/premium-preview/$id'
    | '/verify-employee/$id'
    | '/legal/'
    | '/admin/posts/$slug'
    | '/admin/posts/create'
    | '/admin/posts/'
    | '/admin/posts/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  AppRoute: typeof AppRoute
  AudioRoute: typeof AudioRoute
  AwardsRoute: typeof AwardsRoute
  BillsLawsRoute: typeof BillsLawsRoute
  CommitteeEchoesRoute: typeof CommitteeEchoesRoute
  ConstituencyActionsRoute: typeof ConstituencyActionsRoute
  ContactRoute: typeof ContactRoute
  EconomyRoute: typeof EconomyRoute
  GovernmentRoute: typeof GovernmentRoute
  InterviewsRoute: typeof InterviewsRoute
  LegalRoute: typeof LegalRouteWithChildren
  LegislatureRoute: typeof LegislatureRoute
  NationalAssemblyRoute: typeof NationalAssemblyRoute
  NetworkingRoute: typeof NetworkingRoute
  OpinionRoute: typeof OpinionRoute
  ParliamentRoute: typeof ParliamentRouteWithChildren
  ParliamentaryDiplomacyRoute: typeof ParliamentaryDiplomacyRoute
  ParliamentaryMissionsRoute: typeof ParliamentaryMissionsRoute
  PlenariesRoute: typeof PlenariesRoute
  PoliticsRoute: typeof PoliticsRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  PubRoute: typeof PubRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SenateRoute: typeof SenateRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitemapsRoute: typeof SitemapsRoute
  SystemStatusRoute: typeof SystemStatusRoute
  VideoRoute: typeof VideoRoute
  WatchLiveRoute: typeof WatchLiveRoute
  WeatherRoute: typeof WeatherRoute
  AdminPortalSlugRoute: typeof AdminPortalSlugRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PremiumPreviewIdRoute: typeof PremiumPreviewIdRoute
  VerifyEmployeeIdRoute: typeof VerifyEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-live': {
      id: '/watch-live'
      path: '/watch-live'
      fullPath: '/watch-live'
      preLoaderRoute: typeof WatchLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps': {
      id: '/sitemaps'
      path: '/sitemaps'
      fullPath: '/sitemaps'
      preLoaderRoute: typeof SitemapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senate': {
      id: '/senate'
      path: '/senate'
      fullPath: '/senate'
      preLoaderRoute: typeof SenateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pub': {
      id: '/pub'
      path: '/pub'
      fullPath: '/pub'
      preLoaderRoute: typeof PubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plenaries': {
      id: '/plenaries'
      path: '/plenaries'
      fullPath: '/plenaries'
      preLoaderRoute: typeof PlenariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliamentary-missions': {
      id: '/parliamentary-missions'
      path: '/parliamentary-missions'
      fullPath: '/parliamentary-missions'
      preLoaderRoute: typeof ParliamentaryMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliamentary-diplomacy': {
      id: '/parliamentary-diplomacy'
      path: '/parliamentary-diplomacy'
      fullPath: '/parliamentary-diplomacy'
      preLoaderRoute: typeof ParliamentaryDiplomacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliament': {
      id: '/parliament'
      path: '/parliament'
      fullPath: '/parliament'
      preLoaderRoute: typeof ParliamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinion': {
      id: '/opinion'
      path: '/opinion'
      fullPath: '/opinion'
      preLoaderRoute: typeof OpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking': {
      id: '/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof NetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-assembly': {
      id: '/national-assembly'
      path: '/national-assembly'
      fullPath: '/national-assembly'
      preLoaderRoute: typeof NationalAssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislature': {
      id: '/legislature'
      path: '/legislature'
      fullPath: '/legislature'
      preLoaderRoute: typeof LegislatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constituency-actions': {
      id: '/constituency-actions'
      path: '/constituency-actions'
      fullPath: '/constituency-actions'
      preLoaderRoute: typeof ConstituencyActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee-echoes': {
      id: '/committee-echoes'
      path: '/committee-echoes'
      fullPath: '/committee-echoes'
      preLoaderRoute: typeof CommitteeEchoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills-laws': {
      id: '/bills-laws'
      path: '/bills-laws'
      fullPath: '/bills-laws'
      preLoaderRoute: typeof BillsLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/verify-employee/$id': {
      id: '/verify-employee/$id'
      path: '/verify-employee/$id'
      fullPath: '/verify-employee/$id'
      preLoaderRoute: typeof VerifyEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-preview/$id': {
      id: '/premium-preview/$id'
      path: '/premium-preview/$id'
      fullPath: '/premium-preview/$id'
      preLoaderRoute: typeof PremiumPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliament/mps': {
      id: '/parliament/mps'
      path: '/mps'
      fullPath: '/parliament/mps'
      preLoaderRoute: typeof ParliamentMpsRouteImport
      parentRoute: typeof ParliamentRoute
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/editorial-policy': {
      id: '/legal/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/legal/editorial-policy'
      preLoaderRoute: typeof LegalEditorialPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/copyright-notice': {
      id: '/legal/copyright-notice'
      path: '/copyright-notice'
      fullPath: '/legal/copyright-notice'
      preLoaderRoute: typeof LegalCopyrightNoticeRouteImport
      parentRoute: typeof LegalRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premium': {
      id: '/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminPremiumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mps': {
      id: '/admin/mps'
      path: '/mps'
      fullPath: '/admin/mps'
      preLoaderRoute: typeof AdminMpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/magazines': {
      id: '/admin/magazines'
      path: '/magazines'
      fullPath: '/admin/magazines'
      preLoaderRoute: typeof AdminMagazinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin-portal/$slug': {
      id: '/admin-portal/$slug'
      path: '/admin-portal/$slug'
      fullPath: '/admin-portal/$slug'
      preLoaderRoute: typeof AdminPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$slug': {
      id: '/admin/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/admin/posts/$slug'
      preLoaderRoute: typeof AdminPostsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$slug/edit': {
      id: '/admin/posts/$slug/edit'
      path: '/edit'
      fullPath: '/admin/posts/$slug/edit'
      preLoaderRoute: typeof AdminPostsSlugEditRouteImport
      parentRoute: typeof AdminPostsSlugRoute
    }
  }
}

interface AdminPostsSlugRouteChildren {
  AdminPostsSlugEditRoute: typeof AdminPostsSlugEditRoute
}

const AdminPostsSlugRouteChildren: AdminPostsSlugRouteChildren = {
  AdminPostsSlugEditRoute: AdminPostsSlugEditRoute,
}

const AdminPostsSlugRouteWithChildren = AdminPostsSlugRoute._addFileChildren(
  AdminPostsSlugRouteChildren,
)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminMagazinesRoute: typeof AdminMagazinesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMpsRoute: typeof AdminMpsRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPremiumRoute: typeof AdminPremiumRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminPostsSlugRoute: typeof AdminPostsSlugRouteWithChildren
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminMagazinesRoute: AdminMagazinesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMpsRoute: AdminMpsRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPremiumRoute: AdminPremiumRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminPostsSlugRoute: AdminPostsSlugRouteWithChildren,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LegalRouteChildren {
  LegalCopyrightNoticeRoute: typeof LegalCopyrightNoticeRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalEditorialPolicyRoute: typeof LegalEditorialPolicyRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCopyrightNoticeRoute: LegalCopyrightNoticeRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalEditorialPolicyRoute: LegalEditorialPolicyRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface ParliamentRouteChildren {
  ParliamentMpsRoute: typeof ParliamentMpsRoute
}

const ParliamentRouteChildren: ParliamentRouteChildren = {
  ParliamentMpsRoute: ParliamentMpsRoute,
}

const ParliamentRouteWithChildren = ParliamentRoute._addFileChildren(
  ParliamentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  AppRoute: AppRoute,
  AudioRoute: AudioRoute,
  AwardsRoute: AwardsRoute,
  BillsLawsRoute: BillsLawsRoute,
  CommitteeEchoesRoute: CommitteeEchoesRoute,
  ConstituencyActionsRoute: ConstituencyActionsRoute,
  ContactRoute: ContactRoute,
  EconomyRoute: EconomyRoute,
  GovernmentRoute: GovernmentRoute,
  InterviewsRoute: InterviewsRoute,
  LegalRoute: LegalRouteWithChildren,
  LegislatureRoute: LegislatureRoute,
  NationalAssemblyRoute: NationalAssemblyRoute,
  NetworkingRoute: NetworkingRoute,
  OpinionRoute: OpinionRoute,
  ParliamentRoute: ParliamentRouteWithChildren,
  ParliamentaryDiplomacyRoute: ParliamentaryDiplomacyRoute,
  ParliamentaryMissionsRoute: ParliamentaryMissionsRoute,
  PlenariesRoute: PlenariesRoute,
  PoliticsRoute: PoliticsRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  PubRoute: PubRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SenateRoute: SenateRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitemapsRoute: SitemapsRoute,
  SystemStatusRoute: SystemStatusRoute,
  VideoRoute: VideoRoute,
  WatchLiveRoute: WatchLiveRoute,
  WeatherRoute: WeatherRoute,
  AdminPortalSlugRoute: AdminPortalSlugRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PremiumPreviewIdRoute: PremiumPreviewIdRoute,
  VerifyEmployeeIdRoute: VerifyEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
